#cloud-config

users:
  - default
  - name: ${username}
    primary_group: ${username}
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo, wheel
    package_upgrade: true
    ssh_import_id: None
    lock_passwd: true
    ssh_authorized_keys:
    - ${ssh_public_key}

packages: ${packages}